@startmindmap
* Things I've looked at today
** Getting control of \n personal data you own
*** [[https://perkeep.org/ Perkeep]]
*** [[https://upspin.io/ Upspin]]
*** [[https://solid.inrupt.com/ Solid]]
** Web/Frontend \ndevelopment in Go
*** [[https://github.com/gopherjs/vecty Vecty]]
@endmindmap