@startmindmap
* Things I've looked at today
** Getting control of \n personal data you own
*** Perkeep - https://perkeep.org/
*** Upspin - https://upspin.io/
*** Solid - https://solid.inrupt.com/
@endmindmap